### ISSUE TITLE
Global middleware is executed more than one time per request

### ISSUE THREAD

**Issue by mlstoppa** [ModernINation/RPGWEB#15]
Global middleware procedures are executed inside the routes loop, so in case the wanted route is the fourth in the array gm is executed four times. Is this correct?

**Comment by danlong005** [comment]
Hrm... That is a good point. I think that will have unexpected side effects. Lemme work on that.

**Comment by danlong005** [comment]
I think this is resolved now. When you get a chance, can you test it and make sure you can confirm this.

**Comment by mlstoppa** [comment]
I'll do it by the end of the week. Thank you.

**Comment by mlstoppa** [comment]
IT works, thank you.
